### ISSUE TITLE
有问题啊

### ISSUE THREAD

**Issue by ljbljb007** [zhangkai3110/JD_AutoSubmit#6]
开始识别验证码后提示
Traceback (most recent call last):
  File "jd.py", line 245, in <module>
    a.login()
  File "jd.py", line 89, in login
    imgcode1 = self.rkclient.rk_create(im, 3040)['Result']
KeyError: 'Result'

**Comment by grcp-xw** [comment]
我也是

**Comment by restingmush** [comment]
对啊

**Comment by hmyh1202** [comment]
long time no update
